# Generated by Django 5.1.3 on 2024-12-17 18:19

from django.db import migrations, models

import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='address', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='created', max_length=150, validators=[orders.models.validate_status]),
        ),
    ]
